image: Visual Studio 2017

branches:
  only:
    - master
    - develop

skip_commits:
  files:
    - '**/*.md'

build_script:
  - ps: .\build.ps1

artifacts:
  - path: .\bin\net46
    name: UnityFx.AppStates-net46

  - path: .\bin\netstandard2.0
    name: UnityFx.AppStates-netstandard2.0

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '$(GitVersion_MajorMinorPatch)'
  package_version: '$(GitVersion_SemVer)'
  assembly_version: '$(GitVersion_AssemblySemVer)'
  file_version: '$(GitVersion_MajorMinorPatch).$(GitVersion_CommitsSinceVersionSource)'
  informational_version: '$(GitVersion_InformationalVersion)'
